import {
  SiJavascript,
  SiJavascriptHex,
  SiHtml5,
  SiHtml5Hex,
  SiCss,
  SiCssHex,
  SiTypescript,
  SiTypescriptHex,
  SiReact,
  SiReactHex,
  SiMui,
  SiMuiHex,
  SiTailwindcss,
  SiTailwindcssHex,
  SiAntdesign,
  SiAntdesignHex,
  SiNodedotjs,
  SiNodedotjsHex,
  SiGo,
  SiGoHex,
  SiPostgresql,
  SiPostgresqlHex,
  SiMongodb,
  SiMongodbHex,
  SiGit,
  SiGitHex,
  SiGithubactions,
  SiGithubactionsHex,
  SiGooglecloud,
  SiGooglecloudHex,
  SiJira,
  SiJiraHex,
  SiJest,
  SiJestHex,
  SiCypress,
  SiCypressHex,
  SiTestinglibrary,
  SiTestinglibraryHex,
  SiMockserviceworker,
  SiMockserviceworkerHex,
} from "@icons-pack/react-simple-icons";

export type TechIcon = { icon: typeof SiReact; hex: string };

// Map the tech-tag slugs used in SkillConfig / ProjectConfig to their
// simple-icons brand component + official brand color. Slugs with no
// simple-icons entry (e.g. heroku) are intentionally absent; callers skip them.
export const techIcons: Record<string, TechIcon> = {
  javascript: { icon: SiJavascript, hex: SiJavascriptHex },
  html5: { icon: SiHtml5, hex: SiHtml5Hex },
  css3: { icon: SiCss, hex: SiCssHex },
  typescript: { icon: SiTypescript, hex: SiTypescriptHex },
  react: { icon: SiReact, hex: SiReactHex },
  "material-ui": { icon: SiMui, hex: SiMuiHex },
  tailwindcss: { icon: SiTailwindcss, hex: SiTailwindcssHex },
  antd: { icon: SiAntdesign, hex: SiAntdesignHex },
  nodejs: { icon: SiNodedotjs, hex: SiNodedotjsHex },
  golang: { icon: SiGo, hex: SiGoHex },
  postgresql: { icon: SiPostgresql, hex: SiPostgresqlHex },
  mongodb: { icon: SiMongodb, hex: SiMongodbHex },
  git: { icon: SiGit, hex: SiGitHex },
  "gh-actions": { icon: SiGithubactions, hex: SiGithubactionsHex },
  gcp: { icon: SiGooglecloud, hex: SiGooglecloudHex },
  jira: { icon: SiJira, hex: SiJiraHex },
  jest: { icon: SiJest, hex: SiJestHex },
  cypress: { icon: SiCypress, hex: SiCypressHex },
  "react-testing": { icon: SiTestinglibrary, hex: SiTestinglibraryHex },
  msw: { icon: SiMockserviceworker, hex: SiMockserviceworkerHex },
};
